### PR TITLE
Using system root certificates instead of the old and unmaintained on…

### PR DESCRIPTION
**Pull request by nicksnellockts**
…es in guzzle/http

Just a temporary fix until v3.0 is ready

### CODE REVIEW

**Comment by nicksnellockts** [comment]
I think this change will be required for the Paypal gateway to continue to work after they upgrade their certificate in June 2016.

**Comment by barryvdh** [comment]
Does this always work, or are there consequences for existing users?

**Comment by delatbabel** [comment]
I think this might be required for https://github.com/thephpleague/omnipay-paypal/issues/103

**Comment by delatbabel** [comment]
Or maybe not. The reporter of that issue mentioned that it started working after a http restart. Sorry for the confusion -- nonetheless I think that this is good to have.

**Comment by nicksnellockts** [comment]
I could parameterise this as an option if that is preferable and default it to the existing certificates. That way if a system does not provide certificates for some reason it can continue to rely on the old guzzle ones. I may be the person who delatbabel is referring to. My reload of PHP fixed using access using curls requests, it was still broken trying to access the newly certificated PayPal sandbox using omnipay/PayPal

**Comment by delatbabel** [comment]
That would probably work for me.

**Comment by barryvdh** [comment]
It currently is an option, just pass a Guzzle client to the Gateway with those options set. Going to hold of on this to prevent breakages. If there is an immediate problem, pease re-open!

**Pull request closed without merging**
