### PR TITLE
Add Vindicia gateways to official gateways list

### PR DESCRIPTION
**Pull request by nickyr**
I've created some drivers for [Vindicia](http://www.vindicia.com) and would like to start the process of making these official Omnipay gateways.

Here's the repo: https://github.com/vimeo/omnipay-vindicia

Here's the PR to add it to the list of gateways: https://github.com/thephpleague/omnipay/pull/400

I'm opening this PR based on the instructions in omnipay/omnipay. Let me know what else I need to do to make this happen!

### CODE REVIEW

**Comment by barryvdh** [comment]
You can add the gateway to the readme, but we're not adding them to composer.json anymore

**Comment by nickyr** [comment]
Got it. Are you still making gateways "official" or adding them to the Omnipay organization in any way?

**Comment by barryvdh** [comment]
Nope, we recommend people to use their own organisation.

**Comment by nickyr** [comment]
Ok, thanks!

**Pull request closed without merging**
