### PR TITLE
Add new MasterCard "2" series BIN range support

### LINKED ISSUE #87: New MasterCard "2" series BIN range support?
It is my understanding that starting October 14, 2016 systems will need to begin accepting MasterCards starting with a `2`. _(This also includes any supported gateway providers.)_

Sourced from [wikipedia](https://en.wikipedia.org/wiki/Bank_card_number) and [this post](http://www.foxycart.com/blog/upcoming-mastercard-changes-and-what-you-should-know):
> On November 3, 2014, MasterCard announced that they were introducing a new series of BIN ranges that begin with a “2” (222100–272099). The “2” series BINs will be processed the same as the “51–55” series BINs are today. **They will become active 14 October 2016.**

I checked against `omnipay/common (v2.5.0)` and it seems to add this support, an update would be required to the `$supported_cards` regexes in [CreditCard.php](https://github.com/thephpleague/omnipay-common/blob/550138529e850143af7a87eab8cfe16e72a2f768/src/Omnipay/Common/CreditCard.php#L122)

```php
    protected $supported_cards = array(
        self::BRAND_MASTERCARD => '/^(5[1-5]\d{4}|677189)\d{10}$/', // Regex to be updated?
        // ...
    );
```

Any reason this support should not be added to `omnipay/common`  ahead of the Oct 2016 deadline?

### PR DESCRIPTION
**Pull request by pixelchutes**
Fixes #87

### CODE REVIEW

**Comment by delatbabel** [comment]
Merged. I will not tag this for release because it's not required for live gateways yet, it can go into the next tag.

**Comment by slashP** [comment]
I came here from http://stackoverflow.com/questions/37352795/what-pattern-should-be-used-to-validate-2-bin-mastercard-numbers and wanted to let you know that I'm pretty sure this regex fails for inputs 22x where x is not 1 or 2. So f.ex 2230 xxxx xxxx xxxx would not be a valid card here, but should be.

**Comment by barryvdh** [comment]
Can you submit a PR to fix?

**Comment by delatbabel** [comment]
It looks like the correct range is now 222100-272099.

So the regex to validate the full range (without dashes, because I don't believe that we support them in omnipay) is:

/^5[1-5]\d{2}\d{12}$|^2(?:2(?:2[1-9]|[3-9]\d)|[3-6]\d\d|7(?:[01]\d|20))\d{12}$/

Or adding back in the 677189 BIN for the bizzarro Russian Maestro debit cards:

/^5[1-5]\d{2}\d{12}$|677189\d{10}|^2(?:2(?:2[1-9]|[3-9]\d)|[3-6]\d\d|7(?:[01]\d|20))\d{12}$/

I haven't tested that.

**Comment by pixelchutes** [comment]
Great catch!

Would you like me to prepare a PR with the adjustments, or will you be submitting one?

**Comment by delatbabel** [comment]
Go ahead with the PR if you like.

**Comment by pixelchutes** [comment]
Couldn't the first portion be simplified to:
```
5[1-5]\d{14}
```
Is there any reason why we shouldn't still include the 677189 BIN?

**Comment by pixelchutes** [comment]
I've submitted a new PR with updated regex and test coverage. I ran through quite a few test scenarios and this looks much more solid now.

**Pull request merged**
