### PR TITLE
Check for valid credit card object

### PR DESCRIPTION
**Pull request by aimeos**
This fixes the problem described in https://github.com/thephpleague/omnipay-dummy/issues/2

### CODE REVIEW

**Comment by barryvdh** [comment]
Still not really sure what the underlying problem is. What do you input as creditcard? Is it null or empty array or ..?

**Comment by aimeos** [comment]
If you call getCard() without doing a setCard() before, it returns null since this commit: https://github.com/thephpleague/omnipay-common/commit/3c1efd07af3fc823636149cfabca835b0f871138
Contrary to that, the documentation states that always a CreditCard object is returned.

**Comment by judgej** [comment]
That's strange. The default value for a parameter should be null if not set, [which comes from here](http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/ParameterBag.html#method_get).

**Comment by aimeos** [comment]
Yes, it returns null and that's the reason why this fails:
https://github.com/thephpleague/omnipay-dummy/blob/master/src/Message/AuthorizeRequest.php#L16

**Comment by delatbabel** [comment]
Should this be merged? @judgej  ?

**Comment by judgej** [comment]
If there are no instances where request parameters are not scalar values, then I guess so. I'm not familiar with many of the gateway drivers though, so can't say for sure, but I guess those can be patched individually.

**Comment by delatbabel** [comment]
OK I see no reason not to merge this but I won't tag for the time being until we know this breaks nothing in production.

**Comment by jihoun** [comment]
It seems like this broke the paypal gateway driver as it is using setParameter to specify the list of items in the order.

**Comment by barryvdh** [comment]
This indeed fails when testing paypal with dev stability: https://travis-ci.org/thephpleague/omnipay-paypal/jobs/152325709

**Comment by aimeos** [comment]
The question is now why does it break? For example, `transactionSearch()` only uses an array of scalar parameters if I haven't missed anything.

**Comment by barryvdh** [comment]
You can see the logs on the Travis build:

<details>
<summary>There were 12 errors:</summary>
```
1) Omnipay\PayPal\ExpressGatewayTest::testTransactionSearch
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/ExpressTransactionSearchRequest.php:119
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Helper.php:87
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:133
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/AbstractGateway.php:329
/home/travis/build/thephpleague/omnipay-paypal/src/ExpressGateway.php:156
/home/travis/build/thephpleague/omnipay-paypal/tests/ExpressGatewayTest.php:201
2) Omnipay\PayPal\Message\ExpressAuthorizeRequestTest::testGetDataWithItems
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/AbstractRequest.php:348
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressAuthorizeRequestTest.php:154
3) Omnipay\PayPal\Message\ExpressAuthorizeRequestTest::testDataWithCallback
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/ExpressAuthorizeRequest.php:41
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Helper.php:87
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:133
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressAuthorizeRequestTest.php:247
4) Omnipay\PayPal\Message\ExpressAuthorizeRequestTest::testDataWithCallbackAndNoDefaultShippingOption
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/ExpressAuthorizeRequest.php:41
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Helper.php:87
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:133
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressAuthorizeRequestTest.php:305
5) Omnipay\PayPal\Message\ExpressCompleteAuthorizeRequestTest::testGetDataWithItems
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/AbstractRequest.php:348
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressCompleteAuthorizeRequestTest.php:83
6) Omnipay\PayPal\Message\ExpressCompletePurchaseRequestTest::testGetDataWithItems
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/AbstractRequest.php:348
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressCompletePurchaseRequestTest.php:83
7) Omnipay\PayPal\Message\ExpressTransactionSearchRequestTest::testGetData
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/ExpressTransactionSearchRequest.php:119
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Helper.php:87
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:133
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressTransactionSearchRequestTest.php:46
8) Omnipay\PayPal\Message\ExpressTransactionSearchRequestTest::testAmountWithoutCurrency
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/ExpressTransactionSearchRequest.php:119
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/ExpressTransactionSearchRequestTest.php:86
9) Omnipay\PayPal\Message\RestAuthorizeRequestTest::testGetDataWithoutCard
Omnipay\Common\Exception\InvalidRequestException: The card parameter is required
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:217
/home/travis/build/thephpleague/omnipay-paypal/src/Message/RestAuthorizeRequest.php:262
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/RestAuthorizeRequestTest.php:35
10) Omnipay\PayPal\Message\RestAuthorizeRequestTest::testGetDataWithItems
Omnipay\Common\Exception\InvalidRequestException: The card parameter is required
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:217
/home/travis/build/thephpleague/omnipay-paypal/src/Message/RestAuthorizeRequest.php:262
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/RestAuthorizeRequestTest.php:94
11) Omnipay\PayPal\Message\RestCreatePlanRequestTest::testGetData
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/RestCreatePlanRequest.php:266
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Helper.php:87
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:133
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/RestCreatePlanRequestTest.php:39
12) Omnipay\PayPal\Message\RestCreateSubscriptionRequestTest::testGetData
Omnipay\Common\Exception\RuntimeException: Only scalar values are allowed for parameters
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:174
/home/travis/build/thephpleague/omnipay-paypal/src/Message/RestCreateSubscriptionRequest.php:273
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Helper.php:87
/home/travis/build/thephpleague/omnipay-paypal/vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php:133
/home/travis/build/thephpleague/omnipay-paypal/tests/Message/RestCreateSubscriptionRequestTest.php:27
```</details>

**Comment by aimeos** [comment]
Yes and I tried to analyze the test for `transactionSearch` but don't find the root of the problem

**Comment by jihoun** [comment]
[Here](https://github.com/thephpleague/omnipay-paypal/blob/master/src/Message/AbstractRequest.php#L348) on Paypal gateway, you can see that setParameter is not used with scalar.

**Comment by judgej** [comment]
The core uses `$this->parameters->set('items', $items);` in its [setItems()](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/AbstractRequest.php#L545) which by-passes this scalar check, while the PayPal driver uses `$this->setParameter('items', $items);` which results in this error.

I have a new gateway driver that allows you to pass in an `ItemBag` of extended Items, and that was not breaking, so wondered way PayPal didn't like the change. I guess that was part of the change - PayPal extended the core `setItems()` by copying its internals at the time, and now the internals have changed.

**Comment by aimeos** [comment]
So the fix would be to call
```return $this->setItems($items);```
instead of
```return $this->setParameter('items', $items);```

**Comment by barryvdh** [comment]
But this is still a breaking change,  perhaps for more gateways.

**Comment by judgej** [comment]
@aimeos Wouldn't that break even more gateways? We need to be able to pass an `ItemBag` into `Items` for gateways that use an extended cart, with Sage Pay and PAYONE being two that I know, and now PayPal. That `ItemBag` is not going to be a scalar.

**Comment by aimeos** [comment]
Maybe this affects more gateways. Best option might be to merge the change for 3.0 only. In the meantime, we could replace the exception in `setParameter()` with a deprecation notice.

Items/ItemBag must be added via `setItems()`, not `setParameters()` IMHO

**Comment by judgej** [comment]
So remind me what this check is trying to solve? We know `getItems()` will always return either an `ItemBag` or `null, regardless of what was passed in.`. We know `getCard()` will always return `CreditCard` or `null`, regardless of what was passed in.

It would be ideal if neither returned a `null` so you could always rely on `getItems()->count()` or `getCard()->getNumber()` working, but this is where we are with OmniPay 2.x so we don't want too many surprises I guess.

**Comment by barryvdh** [comment]
So all in favor of reverting this change?

**Comment by judgej** [comment]
> Items/ItemBag must be added via setItems(), not setParameters() IMHO

No argument with this. `setParameters()` is not a public method - it was only used by PayPal internally to extending the `ItemBag`.

**Comment by aimeos** [comment]
It shall solve the problem we had with drivers that require to add objects via `setParameters()` which can't be done in a generic interface offered by a shop application (only configuration strings are possible).

Throwing an exception in `getItems()` and `getCard()` would be a breaking change for 3.0

**Comment by judgej** [comment]
@barryvdh I think so, to get things working again.

@aimeos Is there a distinction not being considered here between configuration data (account IDs, test mode etc), and objects built up from the application (carts and cards)? OmniPay happens to lump the setting of both into one interface.

**Comment by barryvdh** [comment]
Reverted

**Comment by aimeos** [comment]
@judgej Yes, there's a difference. Arbitrary configuration data can be set with `initialize()`, known dynamic data is added to the methods like `purchase()` (e.g. card, transactionId, amount, currency, language, clientIp and the URLs) but gateways requiring things like a XML serializer object to be added via `setParameter()` can't be used at all. They aren't generic and always require a special implementation which make them pretty useless in our environment

**Pull request merged**
