### PR TITLE
New currencies added

### PR DESCRIPTION
**Pull request by dercoder**

### CODE REVIEW

**Comment by barryvdh** [comment]
Where did you get these from?

**Comment by dercoder** [comment]
I got them from 
https://github.com/Payum/iso4217/blob/master/ISO4217.php#L109

**Comment by dercoder** [comment]
Can you also create a new release?

**Comment by judgej** [comment]
Thought about going direct to the source of sources?

http://www.currency-iso.org/dam/downloads/lists/list_one.xml

There is a command-line tool here for mapping that feed onto multiple other formats to automate keeping it up to date:

https://github.com/moneyphp/iso-currencies/blob/master/bin/fetch-update.php

**Comment by dercoder** [comment]
This is a good idea but Bitcoins are missing in this list

**Comment by judgej** [comment]
Are there gateways that accept BTC as a currency? Genuinely curious, since it's not an ISO currency.

**Comment by dercoder** [comment]
Maybe https://github.com/thephpleague/omnipay-coinbase

**Comment by barryvdh** [comment]
In v3 we're using this list directly: https://github.com/alcohol/iso4217

**Comment by judgej** [comment]
Nice. Not duplicating these lists all over the place is, of course, the right way to go. I'm nabbing that for another project too :-)

**Pull request merged**
