### PR TITLE
Add Support for Notifications that passes a TransactionId

### PR DESCRIPTION
**Pull request by GrzegorzBandur**
Add Support for Notifications that passes a TransactionId.

### CODE REVIEW

**Review by PiotrKostanski — APPROVED** [review]

**Comment by barryvdh** [comment]
This is up to the gateway to implement.

**Comment by GrzegorzBandur** [comment]
> This is up to the gateway to implement.

Yes I want to implement this in gateway and check's if gateway has implement this method in multigateway case.

**Comment by barryvdh** [comment]
Yeah but adding it to the interface gives the impression that the method is always available.

**Comment by GrzegorzBandur** [comment]
> Yeah but adding it to the interface gives the impression that the method is always available.

Maybe the solution is to add second interface that extends this interface and check's if Notification implements it?
A lot of providers has this information in Notification and It will be good to get it.

**Comment by barryvdh** [comment]
Yeah but you can still check if the method exists or the data is available. Adding an interface is cleaner but would require all gateways to update.

**Comment by GrzegorzBandur** [comment]
I think that if there is no interface for that nobody will implement method which returns transactionId. If this will be an additional interface that's extends NotificationInterface there will not necessary to update gateways and I future it is possible that getTransactionId in Notification class will be available in gateways published on the internet.

**Pull request closed without merging**
