### PR TITLE
Use Http decorator

### PR DESCRIPTION
**Pull request by barryvdh**
This brings it inline with previous Omnipay

### CODE REVIEW

**Comment by delatbabel** [comment]
Is this OK to merge?

**Comment by barryvdh** [comment]
No

**Comment by barryvdh** [comment]
Sorry for the short reply.  The reason for doubting this is that I'm not sure wether these 'helpers' are required or that we should just stick to 'bare psr-7' and leave it to the gateway drivers to do what is required.

**Comment by judgej** [comment]
Is it a cost-benefit thing, having to maintain that common code for such a variety of gateways, and then finding bugs in the future that are harder to fix without breaking some gateway or other because of some nuance of their particular flavour of XML? Or is that just what I think? I kind of lean towards raw PSR-7, with maybe a page of code snippets in the documentation that driver developers can use as best practice.

**Comment by barryvdh** [comment]
Yeah that is what I'm currently also leaning to. The json is simple enough and the xml is probably too opinionated.

**Pull request closed without merging**
