### PR TITLE
[WIP] Allow symfony3.0

### PR DESCRIPTION
**Pull request by makasim**
I do not use so I am not sure if it work or not.

### CODE REVIEW

**Comment by makasim** [comment]
Works well, though I had to drop php5.3\5.4 support, since symfony3.0 does not support it. May require a major version bump

**Comment by delatbabel** [comment]
This will work in the core but not in any of the gateways.  See this:

https://github.com/thephpleague/omnipay/issues/274#issuecomment-171249397

Omnipay requires guzzle 3.  Guzzle 3 requires Symfony 2.0.  So we have to update the version of Guzzle in use to be able to update Symfony.

**Comment by delatbabel** [comment]
See also #74

**Comment by barryvdh** [comment]
As discussed, this is not possible, due to Guzzle3 dependancies on Symfony2 also.

**Pull request closed without merging**
