### PR TITLE
[3.0][WIP] Some improvements

### PR DESCRIPTION
**Pull request by hugohenrique**
- [x] Upgrade to Guzzle 6
- [x] Upgrade codebase to PSR4
- [x] Moved tests from ``omnipay-tests`` to this repository
- [x] Some improvements on tests

### CODE REVIEW

**Comment by hugohenrique** [comment]
Now the travis is happy :)

**Comment by hugohenrique** [comment]
ping @amacneil @judgej

**Comment by barryvdh** [comment]
Hey, there is a work in progress 3.0 version, but we're using PSR-7 (with Guzzle 6)

**Comment by delatbabel** [comment]
Yeah I don't think this can be merged to the master branch without breaking many things. GuzzleHttp 6 is for 3.0 WIP.

**Comment by hugohenrique** [comment]
So, what's the suggestion?

**Comment by hugohenrique** [comment]
Because my proposal in this PR is not only upgrade the guzzle version, but also move to PSR-4 and remove the need repository "omnipay-tests".

**Comment by barryvdh** [comment]
Hey,

Please check https://github.com/thephpleague/omnipay/tree/3.0
That uses PSR-4, PSR-7, Guzzle6, dropped old php support.

**Pull request closed without merging**
