### PR TITLE
Add getUserMessage() function to response object

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
I am proposing this because some gateways return messages with supplementary data - e.g. Cybersource returns a message indicating invalid data and in a separate field the relevant field names. Also, some processors return reponses with 2 different levels of details e.g 'your transaction was not processed' to the user and 'arrest this person now' to the admin

### CODE REVIEW

**Comment by judgej** [comment]
Out of curiosity, what audience is the getMessage() messages aimed at? It is not clear whether this is for end users or admins/logging. I'm sure it is a mix of the two, depending on what driver/gateway is being used.

So is the idea of getUserMessage() that this is a message that is guaranteed to be safe to put in front of users? What happens if there is no such thing - does this message return nothing/empty/null? I guess it is a guideline that is needed so people use it consistently across the drivers.

**Comment by eileenmcnaughton** [comment]
I was certainly looking to get a message to put in front of users - but I was more thinking about the best message than a guaranteed OK message (ie. fallback to the 'getMessage' if nothing else exists whereas getMessage would be more 'raw' message).

I see your point though, and if it meant 'guaranteed safe' - then the calling code could, I suppose choose whether to return getMessage or a generic message if nothing is returned

**Comment by kayladnls** [comment]
For the gateways that do return more complex messages, or messages for admin/user, shouldn't those implementations offer specific logic to handle that, rather than adding to the common interface? 

I"m thinking that this would be rare, and not apply to most gateways.

**Comment by eileenmcnaughton** [comment]
This is pretty cold from my end so not pushing it now. But, in general the way we integrate multiple processors into a single product & often into a single page - which is why I tend to push for common functions so the calling code can build a form to present and return appropriate messages without having gateway specific code in the calling function.

**Pull request closed without merging**
