### PR TITLE
[3.0?] Implement only HTTP client using httplug

### PR DESCRIPTION
**Pull request by barryvdh**
As we can see that 3.0 refactoring is a pretty big change, also for all gateways, this is more of a Omnipay '2.5', except that because of SemVer, still 3.0 obviously ;). But besides HTTP, no (big) changes.

This uses https://github.com/php-http for HTTP and only replaces the ClientInterface from Guzzle with our own Client (based on HttpPlug, so users can pick their own adapter or we can use a different library later). This keeps using Symfony HttpFoundation (2 or 3)

I would suggest this:

 - omnipay/omnipay would require the guzzle6-adapter by default for easy install for end-users
 - omnipay/common  would require ANY php-http client, don't care which
 - omnipay/tests would require the mock client + guzzle for some extra functionality

Frameworks/apps etc can pick their own adapter by just using common directly with the preferred adapter.

Notable changes required for gateways would be limited to:

 - Change typehint from Guzzle ClientInterface to our own Client
 - Instead of `$client->get('..')->send()`, you get `$client->get('..')` directly.
 - Instead of `$client->createRequest(..)->send()`, you get `$client->sendRequest($client->createRequest(..)`.
- `$headers` must be array (not `null`)
- $body must be string (eg. `http_build_query($data)` or `json_encode($data)` instead of just `$data`.
- `$response->xml()` and `$response->json()` or now `Decoder::xml($response)` and `Decoder::json($response)`

So very limited and all mostly in the `sendData()` method. Not changing of amounts, cards, request query data etc.

Existing changes could be for 4.0, but I don't have time to migrate and test ALL gateways, and based on the progress last year, I assume the rest also doesn't..

### CODE REVIEW

**Comment by delatbabel** [comment]
@barryvdh thanks for this and noted your request to review. I'm currently on leave for Tet holidays (Vietnamese new year) and I'll be back on deck around 6th Feb.  I will try to clear my github inbox before then but I'll be off line for most of the next week or so.

**Comment by barryvdh** [comment]
Okay no problem, just wanted to ping you guys :)

**Comment by judgej** [comment]
Hi @barryvdh, would this weekend be okay to look at this? I'm so far behind with these 3.0 changes, that I would like to spend some time installing, and trying it out to understand it a bit better, and hopefully give a review that is more useful.

**Comment by barryvdh** [comment]
Sure

Note that this is essentially discarding ALL 3.0 changes so far and only building a small change from 2.x. So that was more what I was hoping to get feedback on. 

This would be more of an intermediate release with full end-user BC end just small gateway changes (only the guzzle part)

**Comment by judgej** [comment]
I see, so is this just to keep up with Laravel etc. that have moved on from the older libraries that OmniPay was built for?

Then the current changes on 3.0, will they be rebuilt on top of this? Classes for currency, amounts, more flexible baskets/carts and so on are very important for data consistency IMO, and were certainly heading in the right direction.

**Comment by barryvdh** [comment]
Yeah not really sure about Laravel, but Symfony conflicts (for a while now) and getting more and more requests now ;)

**Comment by barryvdh** [comment]
Related tests PR: https://github.com/thephpleague/omnipay-tests/pull/11
Sample gateway upgrade: https://github.com/thephpleague/omnipay-tests/pull/11

Not really sure why some tests are failing on older versions, probably need to bump some requirement.

> Argument 1 passed to Http\Adapter\Guzzle6\Client::buildClient() must be of the type array, none given, called in /home/travis/build/thephpleague/omnipay-common/vendor/php-http/guzzle6-adapter/src/Client.php on line 31 and defined

**Comment by judgej** [comment]
Trying to set this up to try out yesterday, and got stuck. How would you normally go about installing something like this, along with all its dependencies, and pull in something like `omnipay-example`, without all the dependencies clashing? It's easy enough developing your own packages, as you know what manual overrides to add for any packages that need it, but curious what the normal way of doing it for another package would be.

**Comment by barryvdh** [comment]
I think you should be able to install `dev-3.0-simple` as version to pull in this branch. And also a Guzzle client with `composer require php-http/guzzle6-adapter`

**Comment by judgej** [comment]
Thanks, I'll do that, building something to try up from the ground :-) I think I was just looking at it the wrong way - top down.

**Comment by judgej** [comment]
Hi @barryvdh I suspect I am doing something wrong, but I can't see what. To POST data in a driver, I have replaced this:

    $httpResponse = $this->httpClient->post($this->getEndpoint(), null, $data)->send();

with this:

    $httpResponse = $this->httpClient->post($this->getEndpoint(), [], http_build_query($data));

The body string seems to be created okay, the client is an instance of `Omnipay\Common\Http\Client`. I get a response back from the gateway, but the error it returns implies the body is completely empty, or at least the body cannot be parsed by the gateway. Can you think of a reason this should heppen? (Just had a thought - is `http_build_query()` the right thing to use here? Is there a setting on the client that needs to be triggered to tell it just what is in the body? Or do I need to add a header to do that?)

**Comment by judgej** [comment]
Ah, yes, strange you can be scratching your head all day, then just writing down the problem makes a solution pop up. This works:

    $headers = ['Content-Type' => 'application/x-www-form-urlencoded'];
    $httpResponse = $this->httpClient->post($this->getEndpoint(), $headers, http_build_query($data));

With 2.0 the drivers didn't have to mess around with HTTP details like that.

**Comment by rudott** [comment]
@barryvdh I just created a PR for the mollie package, with these small changes it works with dev-3.0-simple

https://github.com/thephpleague/omnipay-mollie/pull/34/files

**Comment by barryvdh** [comment]
Okay nice. What do you think about the changes? Anything missing or something that could be better?

**Comment by barryvdh** [comment]
Tests are green. I've renamed the old `3.0` branch for the tests and common to `future`, create a `2.5`/`2.1` branch for the old master and merged the `3.0-simple` into master and updated branch-alias.

So you should be able to just require `^3` for common/tests (if you have minimum dev stability)

**Comment by barryvdh** [comment]
I made some tweaks to make it easier to upgrade hopefully; see #147

**Comment by judgej** [comment]
I'm playing with this on a [brand new driver](https://github.com/academe/Omnipay-AuthorizeNetApi) to see how it goes. First thing I've found is that having the phpmoney object and package there makes handling, formatting and sunmming (for basket items) so much easier, safer and more consistent. Absolutely keep that :-)

**Pull request merged**
