### PR TITLE
Added a script to find/add missing Gateways in the composer.json file

### PR DESCRIPTION
**Pull request by detain**
(not sure if this should be sent to omnipay-common or omnipay-example, so sending to both)

It was written while playing with omnipay-example and expects to be in some sort of dir/omnipay/common type directory with other omnipay gateways
installed in dir/*/* for example   dir/omnipay/paypal.

It parses the various vendor/*/*/src/*Gateway.php files looking at the namespace and class name to determin the proper gateway name and searchs
if its already added to the common/composer.json file

Most people should be fine just running the script without worrying about changing anything

Calling it by itself will display a list of gateways missing (if any)
example #1:   ./updategateways.sh
Calling it by first setting the environment variable FIX=1 will insert the missing gateways into the common/composer.json file
example #2:   export FIX=1; ./updategateways.sh
example #3:   FIX=1 ./updategateways.sh

Runing the script found these to add:
* AuthorizeNet_DPM
* Buckaroo_CreditCard
* Eway_Direct
* Eway_RapidDirect
* Eway_RapidShared
* PayPal_Rest

### CODE REVIEW

**Comment by barryvdh** [comment]
Is that gateways array in composer.josn even still used?

**Comment by judgej** [comment]
I believe so. It is in omnipay-common:

https://github.com/thephpleague/omnipay-common/blob/3d7b9253cb86fb39274fa504b4b107dd9a0b2fcd/src/Omnipay/Common/GatewayFactory.php#L116

**Comment by barryvdh** [comment]
Yeah but that doesn't make much sense imho, because it can't know about any 3rd party gateways and it doesn't have all gateways installed by default.

**Comment by judgej** [comment]
The example application does try to install everything it knows about, so a lot of gateways will be installed. But I agree, it's not really the way to do it (trying to develop a new gateway while trying it out with the example application is a pain).

This is something I've wondered about for a while: can you ask composer, from a package, what is installed? We don't care where they are installed, just so long as they are installed somewhere, then each can be checked to look for some kind of signature, maybe a class and method that all gateways will uniquely have.

**Comment by barryvdh** [comment]
You could let every gateway add something to the extra array in composer.json and search all of them, or create a package type +plugin which creates a list of all gateways, or autoload a file which announces the gateway to some static omnipay registry. But all not very great.

Question could be, why would you need all of the gateways? Every gateway is probably a bit different and needs some key/token/id, so you can't just blindly give a user all options.

If it's for the developer, a good IDE could complete Moet gateways, and Phpstorm can use a meta file to auto complete the factory.

**Comment by judgej** [comment]
The example application cuts through what the documentation lacks. I could not get my head around what OmniPay did and did not do, and how it worked, until I installed the example application and then a lot of things made more sense. It is useful in that respect. We are coming at this with a lot of knowledge about how to develop with OmniPay that really is not very obvious or intuitive.

Each gateway declares what tokens and auth details they need, and the example application picks these up nicely. It doesn't handle notify callbacks (and couldn't unless run on a public domain anyway) but it would be nice (though not important) to get that support in for a few gateways at least.

In a developed application though, I don't see any any real need to do this, i.e. to get a listing of what gateways have been installed. So with that in mind, I don't think omnipay-common needs to get involved in finding this list of gateways.

**Comment by barryvdh** [comment]
Closing due to inactivity. If still relevant, please re-open!

**Pull request closed without merging**
